language: php

sudo: false

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION='^3'
    - php: 7.1
      env: SYMFONY_VERSION='^4'
    - php: 7.2
      env: SYMFONY_VERSION='^4'

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer require --no-update symfony/browser-kit:$SYMFONY_VERSION

install:
  - composer install -n --prefer-dist

script: vendor/bin/phpunit -v --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
